/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { InvoiceService } from "../invoice.service";
import { InvoiceCreateInput } from "./InvoiceCreateInput";
import { Invoice } from "./Invoice";
import { InvoiceFindManyArgs } from "./InvoiceFindManyArgs";
import { InvoiceWhereUniqueInput } from "./InvoiceWhereUniqueInput";
import { InvoiceUpdateInput } from "./InvoiceUpdateInput";
import { PaymentFindManyArgs } from "../../payment/base/PaymentFindManyArgs";
import { Payment } from "../../payment/base/Payment";
import { PaymentWhereUniqueInput } from "../../payment/base/PaymentWhereUniqueInput";
import { TransportDetailFindManyArgs } from "../../transportDetail/base/TransportDetailFindManyArgs";
import { TransportDetail } from "../../transportDetail/base/TransportDetail";
import { TransportDetailWhereUniqueInput } from "../../transportDetail/base/TransportDetailWhereUniqueInput";

export class InvoiceControllerBase {
  constructor(protected readonly service: InvoiceService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Invoice })
  async createInvoice(
    @common.Body() data: InvoiceCreateInput
  ): Promise<Invoice> {
    return await this.service.createInvoice({
      data: {
        ...data,

        customer: data.customer
          ? {
              connect: data.customer,
            }
          : undefined,
      },
      select: {
        amount: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        date: true,
        id: true,
        invoiceNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Invoice] })
  @ApiNestedQuery(InvoiceFindManyArgs)
  async invoices(@common.Req() request: Request): Promise<Invoice[]> {
    const args = plainToClass(InvoiceFindManyArgs, request.query);
    return this.service.invoices({
      ...args,
      select: {
        amount: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        date: true,
        id: true,
        invoiceNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Invoice })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async invoice(
    @common.Param() params: InvoiceWhereUniqueInput
  ): Promise<Invoice | null> {
    const result = await this.service.invoice({
      where: params,
      select: {
        amount: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        date: true,
        id: true,
        invoiceNumber: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Invoice })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateInvoice(
    @common.Param() params: InvoiceWhereUniqueInput,
    @common.Body() data: InvoiceUpdateInput
  ): Promise<Invoice | null> {
    try {
      return await this.service.updateInvoice({
        where: params,
        data: {
          ...data,

          customer: data.customer
            ? {
                connect: data.customer,
              }
            : undefined,
        },
        select: {
          amount: true,
          createdAt: true,

          customer: {
            select: {
              id: true,
            },
          },

          date: true,
          id: true,
          invoiceNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Invoice })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteInvoice(
    @common.Param() params: InvoiceWhereUniqueInput
  ): Promise<Invoice | null> {
    try {
      return await this.service.deleteInvoice({
        where: params,
        select: {
          amount: true,
          createdAt: true,

          customer: {
            select: {
              id: true,
            },
          },

          date: true,
          id: true,
          invoiceNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/payments")
  @ApiNestedQuery(PaymentFindManyArgs)
  async findPayments(
    @common.Req() request: Request,
    @common.Param() params: InvoiceWhereUniqueInput
  ): Promise<Payment[]> {
    const query = plainToClass(PaymentFindManyArgs, request.query);
    const results = await this.service.findPayments(params.id, {
      ...query,
      select: {
        amount: true,
        createdAt: true,
        id: true,

        invoice: {
          select: {
            id: true,
          },
        },

        paymentDate: true,
        paymentMethod: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/payments")
  async connectPayments(
    @common.Param() params: InvoiceWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        connect: body,
      },
    };
    await this.service.updateInvoice({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/payments")
  async updatePayments(
    @common.Param() params: InvoiceWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        set: body,
      },
    };
    await this.service.updateInvoice({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/payments")
  async disconnectPayments(
    @common.Param() params: InvoiceWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        disconnect: body,
      },
    };
    await this.service.updateInvoice({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/transportDetails")
  @ApiNestedQuery(TransportDetailFindManyArgs)
  async findTransportDetails(
    @common.Req() request: Request,
    @common.Param() params: InvoiceWhereUniqueInput
  ): Promise<TransportDetail[]> {
    const query = plainToClass(TransportDetailFindManyArgs, request.query);
    const results = await this.service.findTransportDetails(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        invoice: {
          select: {
            id: true,
          },
        },

        scheduleDate: true,
        transportationMode: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/transportDetails")
  async connectTransportDetails(
    @common.Param() params: InvoiceWhereUniqueInput,
    @common.Body() body: TransportDetailWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transportDetails: {
        connect: body,
      },
    };
    await this.service.updateInvoice({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/transportDetails")
  async updateTransportDetails(
    @common.Param() params: InvoiceWhereUniqueInput,
    @common.Body() body: TransportDetailWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transportDetails: {
        set: body,
      },
    };
    await this.service.updateInvoice({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/transportDetails")
  async disconnectTransportDetails(
    @common.Param() params: InvoiceWhereUniqueInput,
    @common.Body() body: TransportDetailWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transportDetails: {
        disconnect: body,
      },
    };
    await this.service.updateInvoice({
      where: params,
      data,
      select: { id: true },
    });
  }
}
